version: '2'
services:
  solr:
    restart: always
    container_name: solr_app
    image: solr:7.2-alpine
    volumes:
      - ./solr_app/scripts:/docker-entrypoint-initdb.d/
    ports:
      - 8983:8983
  app:
    restart: always
    container_name: search_api
    build:
        context: ./search_api
        dockerfile: Dockerfile.test
    ports:
      - 5000:5000
    volumes:
      - ./search_api:/usr/local/search_api/
