# Dockerfile inspired by "Timothy Ko <tk2@illinois.edu>" from https://medium.freecodecamp.org/docker-development-workflow-a-guide-with-flask-and-postgres-db1a1843044a

FROM python:3.6

RUN apt-get update

WORKDIR /usr/local/search_api/

COPY search_api/ /usr/local/search_api/

RUN pip install --upgrade pip
RUN pip install pip-tools
RUN pip-compile > requirements.txt

# argumento -e é usado para instalar módulos do argumento 'extra_requires' e
# -r indica para instalar os módulos e dependências do argumento 'install_requires'
RUN pip install -e .[dev] -r requirements.txt

ENV FLASK_ENV="docker"

EXPOSE 5000

CMD python search_api/tests.py
